name: libasm
on:
  push:
    branches:
      - main
      - develop/libc
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install ASM dependencies
        run: sudo apt-get install nasm
      - name: Builds static library libasm.a
        run: make
      - name: Run test suite on static library functions
        run: make test
